spin_manifest_version = 2

[application]
authors = ["Rajat Jindal<rajatjindal83@gmail.com>"]
description = "setup"
name = "setup wasmtime"
version = "0.1.0"

[[trigger.ghaction]]
component = "hello-world"
env = []

[component.hello-world]
source = "main.wasm"
allowed_outbound_hosts = []
build = ["tinygo build -x -target=wasip2 --wit-package $(go list -mod=readonly -m -f '{{.Dir}}' github.com/rajatjindal/wasm-actions-sdk)/wit --wit-world cli -o main.wasm -x -work main.go"]