name: Deploy Good First Issue Bot
on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Run action using spin
        run: printenv

      - name: setup spin
        uses: fermyon/actions/spin/setup@v1
        with:
          github_token: ${{ github.token }}
        
      - name: setup spin ghaction plugin
        run: spin plugin install --url https://github.com/rajatjindal/spin-trigger-ghaction/releases/download/canary/trigger-ghaction.json --yes

      - name: Run action using spin
        run: mkdir spin-ghactions-tmp && spin up - --version v0.3.0
      
      - name: verify the setup
        run: ./spin-ghactions-tmp/kubectl-reverse_proxy -h
      

